### ISSUE TITLE
Missing default model.20120919 after building from source code

### ISSUE THREAD

**Issue by zjiang91** [brendano/ark-tweet-nlp#31]
After I use `mvn package` to build the ark-tweet-nlp-0.3.2.jar, It will report an IOException when I run `./runTagger.sh examples/example_tweets.txt`.

Details:
```
Exception in thread "main" java.io.IOException: Neither file nor resource found for: /cmu/arktweetnlp/model.20120919
	at cmu.arktweetnlp.util.BasicFileIO.openFileOrResource(BasicFileIO.java:250)
	at cmu.arktweetnlp.impl.Model.loadModelFromText(Model.java:409)
	at cmu.arktweetnlp.Tagger.loadModel(Tagger.java:40)
	at cmu.arktweetnlp.RunTagger.runTagger(RunTagger.java:85)
	at cmu.arktweetnlp.RunTagger.main(RunTagger.java:373)
```

**Comment by brendano** [comment]
i'm commenting on PR #32

**Comment by brendano** [comment]
the way this is supposed to be done is, you have to download the model file into the right place (as done in PR #32).
